# Generated by Django 5.0.2 on 2025-04-23 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_departamento_proyecto_trabajador_tarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='desarrolladores',
            field=models.ManyToManyField(blank=True, related_name='proyectos_participando', to='api.trabajador'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='api.departamento'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_responsable', to='api.trabajador'),
        ),
    ]
