# Generated by Django 5.0.2 on 2025-04-23 00:26

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proyecto_desarrolladores_alter_proyecto_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tareas_asignadas',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Run data migration operation to convert from Trabajador to User
        migrations.RunSQL(
            """
            UPDATE api_tarea 
            SET asignado_a_id = (
                SELECT user_id 
                FROM api_trabajador 
                WHERE api_trabajador.id = api_tarea.asignado_a_id
            )
            WHERE asignado_a_id IS NOT NULL;
            """,
            reverse_sql="""
            -- Cannot automatically reverse this migration
            """
        ),
    ]
