# Generated by Django 5.0.2 on 2025-04-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250422_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='departamento',
        ),
    ]
