# Generated by Django 5.0.2 on 2025-04-23 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20250422_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='proyectos_creados',
                to='api.user',
            ),
        ),
        migrations.RunSQL(
            """
            -- Eliminar tareas existentes que dependen de proyectos
            DELETE FROM api_tarea;
            
            -- Eliminar todos los proyectos existentes
            DELETE FROM api_proyecto;
            
            -- Eliminar relaciones en la tabla intermedia
            DELETE FROM api_proyecto_desarrolladores;
            
            -- Si no hay usuarios, crear un usuario administrador
            INSERT OR IGNORE INTO api_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)
            SELECT 1, 'pbkdf2_sha256$720000$8Wr9aZv3dS02qpfOlnYxqA$eKSfL7/i4kUcYa8Ff+ekFJpPpnGY1pHfUQiTIZO5SFI=', NULL, 1, 'admin', '', '', 'admin@example.com', 1, 1, CURRENT_TIMESTAMP
            WHERE NOT EXISTS (SELECT 1 FROM api_user WHERE id = 1);
            """,
            reverse_sql="""
            -- No es posible revertir esta migración
            """
        ),
    ]
